/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EventsSlugIndexRouteImport } from './routes/events.$slug.index'
import { Route as EventsSlugGalleryRouteImport } from './routes/events.$slug.gallery'
import { Route as EventsSlugResultsRouteImport } from './routes/events.$slug.results'
import { Route as EventsSlugSubmitRouteImport } from './routes/events.$slug.submit'
import { Route as EventsSlugTeamRouteImport } from './routes/events.$slug.team'
import { Route as EventsSlugVoteRouteImport } from './routes/events.$slug.vote'
import { Route as OrganizerEventsIndexRouteImport } from './routes/organizer.events.index'
import { Route as EventsSlugJudgeIndexRouteImport } from './routes/events.$slug.judge.index'
import { Route as EventsSlugJudgeCompareRouteImport } from './routes/events.$slug.judge.compare'
import { Route as EventsSlugJudgeHistoryRouteImport } from './routes/events.$slug.judge.history'
import { Route as EventsSlugProjectsProjectIdRouteImport } from './routes/events.$slug.projects.$projectId'
import { Route as OrganizerEventsSlugAuditRouteImport } from './routes/organizer.events.$slug.audit'
import { Route as OrganizerEventsSlugDashboardRouteImport } from './routes/organizer.events.$slug.dashboard'
import { Route as OrganizerEventsSlugExportRouteImport } from './routes/organizer.events.$slug.export'
import { Route as OrganizerEventsSlugJudgesRouteImport } from './routes/organizer.events.$slug.judges'
import { Route as OrganizerEventsSlugResultsRouteImport } from './routes/organizer.events.$slug.results'
import { Route as OrganizerEventsSlugRubricRouteImport } from './routes/organizer.events.$slug.rubric'
import { Route as OrganizerEventsSlugSetupRouteImport } from './routes/organizer.events.$slug.setup'
import { Route as OrganizerEventsSlugProjectsProjectIdWhyRouteImport } from './routes/organizer.events.$slug.projects.$projectId.why'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/events/$slug/',
  path: '/events/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugGalleryRoute = EventsSlugGalleryRouteImport.update({
  id: '/events/$slug/gallery',
  path: '/events/$slug/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugResultsRoute = EventsSlugResultsRouteImport.update({
  id: '/events/$slug/results',
  path: '/events/$slug/results',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugSubmitRoute = EventsSlugSubmitRouteImport.update({
  id: '/events/$slug/submit',
  path: '/events/$slug/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugTeamRoute = EventsSlugTeamRouteImport.update({
  id: '/events/$slug/team',
  path: '/events/$slug/team',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugVoteRoute = EventsSlugVoteRouteImport.update({
  id: '/events/$slug/vote',
  path: '/events/$slug/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsIndexRoute = OrganizerEventsIndexRouteImport.update({
  id: '/organizer/events/',
  path: '/organizer/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugJudgeIndexRoute = EventsSlugJudgeIndexRouteImport.update({
  id: '/events/$slug/judge/',
  path: '/events/$slug/judge/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugJudgeCompareRoute = EventsSlugJudgeCompareRouteImport.update({
  id: '/events/$slug/judge/compare',
  path: '/events/$slug/judge/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugJudgeHistoryRoute = EventsSlugJudgeHistoryRouteImport.update({
  id: '/events/$slug/judge/history',
  path: '/events/$slug/judge/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugProjectsProjectIdRoute =
  EventsSlugProjectsProjectIdRouteImport.update({
    id: '/events/$slug/projects/$projectId',
    path: '/events/$slug/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsSlugAuditRoute =
  OrganizerEventsSlugAuditRouteImport.update({
    id: '/organizer/events/$slug/audit',
    path: '/organizer/events/$slug/audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsSlugDashboardRoute =
  OrganizerEventsSlugDashboardRouteImport.update({
    id: '/organizer/events/$slug/dashboard',
    path: '/organizer/events/$slug/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsSlugExportRoute =
  OrganizerEventsSlugExportRouteImport.update({
    id: '/organizer/events/$slug/export',
    path: '/organizer/events/$slug/export',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsSlugJudgesRoute =
  OrganizerEventsSlugJudgesRouteImport.update({
    id: '/organizer/events/$slug/judges',
    path: '/organizer/events/$slug/judges',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsSlugResultsRoute =
  OrganizerEventsSlugResultsRouteImport.update({
    id: '/organizer/events/$slug/results',
    path: '/organizer/events/$slug/results',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsSlugRubricRoute =
  OrganizerEventsSlugRubricRouteImport.update({
    id: '/organizer/events/$slug/rubric',
    path: '/organizer/events/$slug/rubric',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsSlugSetupRoute =
  OrganizerEventsSlugSetupRouteImport.update({
    id: '/organizer/events/$slug/setup',
    path: '/organizer/events/$slug/setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsSlugProjectsProjectIdWhyRoute =
  OrganizerEventsSlugProjectsProjectIdWhyRouteImport.update({
    id: '/organizer/events/$slug/projects/$projectId/why',
    path: '/organizer/events/$slug/projects/$projectId/why',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$slug/gallery': typeof EventsSlugGalleryRoute
  '/events/$slug/results': typeof EventsSlugResultsRoute
  '/events/$slug/submit': typeof EventsSlugSubmitRoute
  '/events/$slug/team': typeof EventsSlugTeamRoute
  '/events/$slug/vote': typeof EventsSlugVoteRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/organizer/events/': typeof OrganizerEventsIndexRoute
  '/events/$slug/judge/compare': typeof EventsSlugJudgeCompareRoute
  '/events/$slug/judge/history': typeof EventsSlugJudgeHistoryRoute
  '/events/$slug/projects/$projectId': typeof EventsSlugProjectsProjectIdRoute
  '/organizer/events/$slug/audit': typeof OrganizerEventsSlugAuditRoute
  '/organizer/events/$slug/dashboard': typeof OrganizerEventsSlugDashboardRoute
  '/organizer/events/$slug/export': typeof OrganizerEventsSlugExportRoute
  '/organizer/events/$slug/judges': typeof OrganizerEventsSlugJudgesRoute
  '/organizer/events/$slug/results': typeof OrganizerEventsSlugResultsRoute
  '/organizer/events/$slug/rubric': typeof OrganizerEventsSlugRubricRoute
  '/organizer/events/$slug/setup': typeof OrganizerEventsSlugSetupRoute
  '/events/$slug/judge/': typeof EventsSlugJudgeIndexRoute
  '/organizer/events/$slug/projects/$projectId/why': typeof OrganizerEventsSlugProjectsProjectIdWhyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$slug/gallery': typeof EventsSlugGalleryRoute
  '/events/$slug/results': typeof EventsSlugResultsRoute
  '/events/$slug/submit': typeof EventsSlugSubmitRoute
  '/events/$slug/team': typeof EventsSlugTeamRoute
  '/events/$slug/vote': typeof EventsSlugVoteRoute
  '/events/$slug': typeof EventsSlugIndexRoute
  '/organizer/events': typeof OrganizerEventsIndexRoute
  '/events/$slug/judge/compare': typeof EventsSlugJudgeCompareRoute
  '/events/$slug/judge/history': typeof EventsSlugJudgeHistoryRoute
  '/events/$slug/projects/$projectId': typeof EventsSlugProjectsProjectIdRoute
  '/organizer/events/$slug/audit': typeof OrganizerEventsSlugAuditRoute
  '/organizer/events/$slug/dashboard': typeof OrganizerEventsSlugDashboardRoute
  '/organizer/events/$slug/export': typeof OrganizerEventsSlugExportRoute
  '/organizer/events/$slug/judges': typeof OrganizerEventsSlugJudgesRoute
  '/organizer/events/$slug/results': typeof OrganizerEventsSlugResultsRoute
  '/organizer/events/$slug/rubric': typeof OrganizerEventsSlugRubricRoute
  '/organizer/events/$slug/setup': typeof OrganizerEventsSlugSetupRoute
  '/events/$slug/judge': typeof EventsSlugJudgeIndexRoute
  '/organizer/events/$slug/projects/$projectId/why': typeof OrganizerEventsSlugProjectsProjectIdWhyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$slug/gallery': typeof EventsSlugGalleryRoute
  '/events/$slug/results': typeof EventsSlugResultsRoute
  '/events/$slug/submit': typeof EventsSlugSubmitRoute
  '/events/$slug/team': typeof EventsSlugTeamRoute
  '/events/$slug/vote': typeof EventsSlugVoteRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/organizer/events/': typeof OrganizerEventsIndexRoute
  '/events/$slug/judge/compare': typeof EventsSlugJudgeCompareRoute
  '/events/$slug/judge/history': typeof EventsSlugJudgeHistoryRoute
  '/events/$slug/projects/$projectId': typeof EventsSlugProjectsProjectIdRoute
  '/organizer/events/$slug/audit': typeof OrganizerEventsSlugAuditRoute
  '/organizer/events/$slug/dashboard': typeof OrganizerEventsSlugDashboardRoute
  '/organizer/events/$slug/export': typeof OrganizerEventsSlugExportRoute
  '/organizer/events/$slug/judges': typeof OrganizerEventsSlugJudgesRoute
  '/organizer/events/$slug/results': typeof OrganizerEventsSlugResultsRoute
  '/organizer/events/$slug/rubric': typeof OrganizerEventsSlugRubricRoute
  '/organizer/events/$slug/setup': typeof OrganizerEventsSlugSetupRoute
  '/events/$slug/judge/': typeof EventsSlugJudgeIndexRoute
  '/organizer/events/$slug/projects/$projectId/why': typeof OrganizerEventsSlugProjectsProjectIdWhyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/events/$slug/gallery'
    | '/events/$slug/results'
    | '/events/$slug/submit'
    | '/events/$slug/team'
    | '/events/$slug/vote'
    | '/events/$slug/'
    | '/organizer/events/'
    | '/events/$slug/judge/compare'
    | '/events/$slug/judge/history'
    | '/events/$slug/projects/$projectId'
    | '/organizer/events/$slug/audit'
    | '/organizer/events/$slug/dashboard'
    | '/organizer/events/$slug/export'
    | '/organizer/events/$slug/judges'
    | '/organizer/events/$slug/results'
    | '/organizer/events/$slug/rubric'
    | '/organizer/events/$slug/setup'
    | '/events/$slug/judge/'
    | '/organizer/events/$slug/projects/$projectId/why'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/events/$slug/gallery'
    | '/events/$slug/results'
    | '/events/$slug/submit'
    | '/events/$slug/team'
    | '/events/$slug/vote'
    | '/events/$slug'
    | '/organizer/events'
    | '/events/$slug/judge/compare'
    | '/events/$slug/judge/history'
    | '/events/$slug/projects/$projectId'
    | '/organizer/events/$slug/audit'
    | '/organizer/events/$slug/dashboard'
    | '/organizer/events/$slug/export'
    | '/organizer/events/$slug/judges'
    | '/organizer/events/$slug/results'
    | '/organizer/events/$slug/rubric'
    | '/organizer/events/$slug/setup'
    | '/events/$slug/judge'
    | '/organizer/events/$slug/projects/$projectId/why'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/events/$slug/gallery'
    | '/events/$slug/results'
    | '/events/$slug/submit'
    | '/events/$slug/team'
    | '/events/$slug/vote'
    | '/events/$slug/'
    | '/organizer/events/'
    | '/events/$slug/judge/compare'
    | '/events/$slug/judge/history'
    | '/events/$slug/projects/$projectId'
    | '/organizer/events/$slug/audit'
    | '/organizer/events/$slug/dashboard'
    | '/organizer/events/$slug/export'
    | '/organizer/events/$slug/judges'
    | '/organizer/events/$slug/results'
    | '/organizer/events/$slug/rubric'
    | '/organizer/events/$slug/setup'
    | '/events/$slug/judge/'
    | '/organizer/events/$slug/projects/$projectId/why'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EventsSlugGalleryRoute: typeof EventsSlugGalleryRoute
  EventsSlugResultsRoute: typeof EventsSlugResultsRoute
  EventsSlugSubmitRoute: typeof EventsSlugSubmitRoute
  EventsSlugTeamRoute: typeof EventsSlugTeamRoute
  EventsSlugVoteRoute: typeof EventsSlugVoteRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
  OrganizerEventsIndexRoute: typeof OrganizerEventsIndexRoute
  EventsSlugJudgeCompareRoute: typeof EventsSlugJudgeCompareRoute
  EventsSlugJudgeHistoryRoute: typeof EventsSlugJudgeHistoryRoute
  EventsSlugProjectsProjectIdRoute: typeof EventsSlugProjectsProjectIdRoute
  OrganizerEventsSlugAuditRoute: typeof OrganizerEventsSlugAuditRoute
  OrganizerEventsSlugDashboardRoute: typeof OrganizerEventsSlugDashboardRoute
  OrganizerEventsSlugExportRoute: typeof OrganizerEventsSlugExportRoute
  OrganizerEventsSlugJudgesRoute: typeof OrganizerEventsSlugJudgesRoute
  OrganizerEventsSlugResultsRoute: typeof OrganizerEventsSlugResultsRoute
  OrganizerEventsSlugRubricRoute: typeof OrganizerEventsSlugRubricRoute
  OrganizerEventsSlugSetupRoute: typeof OrganizerEventsSlugSetupRoute
  EventsSlugJudgeIndexRoute: typeof EventsSlugJudgeIndexRoute
  OrganizerEventsSlugProjectsProjectIdWhyRoute: typeof OrganizerEventsSlugProjectsProjectIdWhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/events/$slug'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/gallery': {
      id: '/events/$slug/gallery'
      path: '/events/$slug/gallery'
      fullPath: '/events/$slug/gallery'
      preLoaderRoute: typeof EventsSlugGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/results': {
      id: '/events/$slug/results'
      path: '/events/$slug/results'
      fullPath: '/events/$slug/results'
      preLoaderRoute: typeof EventsSlugResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/submit': {
      id: '/events/$slug/submit'
      path: '/events/$slug/submit'
      fullPath: '/events/$slug/submit'
      preLoaderRoute: typeof EventsSlugSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/team': {
      id: '/events/$slug/team'
      path: '/events/$slug/team'
      fullPath: '/events/$slug/team'
      preLoaderRoute: typeof EventsSlugTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/vote': {
      id: '/events/$slug/vote'
      path: '/events/$slug/vote'
      fullPath: '/events/$slug/vote'
      preLoaderRoute: typeof EventsSlugVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/': {
      id: '/organizer/events/'
      path: '/organizer/events'
      fullPath: '/organizer/events/'
      preLoaderRoute: typeof OrganizerEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/judge/': {
      id: '/events/$slug/judge/'
      path: '/events/$slug/judge'
      fullPath: '/events/$slug/judge/'
      preLoaderRoute: typeof EventsSlugJudgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/judge/compare': {
      id: '/events/$slug/judge/compare'
      path: '/events/$slug/judge/compare'
      fullPath: '/events/$slug/judge/compare'
      preLoaderRoute: typeof EventsSlugJudgeCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/judge/history': {
      id: '/events/$slug/judge/history'
      path: '/events/$slug/judge/history'
      fullPath: '/events/$slug/judge/history'
      preLoaderRoute: typeof EventsSlugJudgeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/projects/$projectId': {
      id: '/events/$slug/projects/$projectId'
      path: '/events/$slug/projects/$projectId'
      fullPath: '/events/$slug/projects/$projectId'
      preLoaderRoute: typeof EventsSlugProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$slug/audit': {
      id: '/organizer/events/$slug/audit'
      path: '/organizer/events/$slug/audit'
      fullPath: '/organizer/events/$slug/audit'
      preLoaderRoute: typeof OrganizerEventsSlugAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$slug/dashboard': {
      id: '/organizer/events/$slug/dashboard'
      path: '/organizer/events/$slug/dashboard'
      fullPath: '/organizer/events/$slug/dashboard'
      preLoaderRoute: typeof OrganizerEventsSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$slug/export': {
      id: '/organizer/events/$slug/export'
      path: '/organizer/events/$slug/export'
      fullPath: '/organizer/events/$slug/export'
      preLoaderRoute: typeof OrganizerEventsSlugExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$slug/judges': {
      id: '/organizer/events/$slug/judges'
      path: '/organizer/events/$slug/judges'
      fullPath: '/organizer/events/$slug/judges'
      preLoaderRoute: typeof OrganizerEventsSlugJudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$slug/results': {
      id: '/organizer/events/$slug/results'
      path: '/organizer/events/$slug/results'
      fullPath: '/organizer/events/$slug/results'
      preLoaderRoute: typeof OrganizerEventsSlugResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$slug/rubric': {
      id: '/organizer/events/$slug/rubric'
      path: '/organizer/events/$slug/rubric'
      fullPath: '/organizer/events/$slug/rubric'
      preLoaderRoute: typeof OrganizerEventsSlugRubricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$slug/setup': {
      id: '/organizer/events/$slug/setup'
      path: '/organizer/events/$slug/setup'
      fullPath: '/organizer/events/$slug/setup'
      preLoaderRoute: typeof OrganizerEventsSlugSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$slug/projects/$projectId/why': {
      id: '/organizer/events/$slug/projects/$projectId/why'
      path: '/organizer/events/$slug/projects/$projectId/why'
      fullPath: '/organizer/events/$slug/projects/$projectId/why'
      preLoaderRoute: typeof OrganizerEventsSlugProjectsProjectIdWhyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EventsSlugGalleryRoute: EventsSlugGalleryRoute,
  EventsSlugResultsRoute: EventsSlugResultsRoute,
  EventsSlugSubmitRoute: EventsSlugSubmitRoute,
  EventsSlugTeamRoute: EventsSlugTeamRoute,
  EventsSlugVoteRoute: EventsSlugVoteRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
  OrganizerEventsIndexRoute: OrganizerEventsIndexRoute,
  EventsSlugJudgeCompareRoute: EventsSlugJudgeCompareRoute,
  EventsSlugJudgeHistoryRoute: EventsSlugJudgeHistoryRoute,
  EventsSlugProjectsProjectIdRoute: EventsSlugProjectsProjectIdRoute,
  OrganizerEventsSlugAuditRoute: OrganizerEventsSlugAuditRoute,
  OrganizerEventsSlugDashboardRoute: OrganizerEventsSlugDashboardRoute,
  OrganizerEventsSlugExportRoute: OrganizerEventsSlugExportRoute,
  OrganizerEventsSlugJudgesRoute: OrganizerEventsSlugJudgesRoute,
  OrganizerEventsSlugResultsRoute: OrganizerEventsSlugResultsRoute,
  OrganizerEventsSlugRubricRoute: OrganizerEventsSlugRubricRoute,
  OrganizerEventsSlugSetupRoute: OrganizerEventsSlugSetupRoute,
  EventsSlugJudgeIndexRoute: EventsSlugJudgeIndexRoute,
  OrganizerEventsSlugProjectsProjectIdWhyRoute:
    OrganizerEventsSlugProjectsProjectIdWhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
